#!/bin/bash -e

PROJECT=`readlink -f $0`
PROJECT=`dirname $PROJECT`
TARGET=/tmp/jboss-spring-tx
SCRIPTS=$TARGET/hulte-scripts
CURR=CURRENT-SNAPSHOT

# (re)create the target folder
if [ -d $TARGET ]; then
    rm -r $TARGET
fi
mkdir $TARGET

# install JBoss & modules
echo "installing JBoss & modules"
for module in `ls $PROJECT/bin | egrep "\\.tgz$"`; do
    tar -C $TARGET -xf $PROJECT/bin/$module
done

# start JBoss in the backrgound
cd $TARGET
echo "starting JBoss"
# export JAVA_OPTS="-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y"
bin/standalone.sh &
sleep 5 # TODO please improve me...

# initialize modules
for script in `ls $SCRIPTS/*/*.cli`; do
    echo "> $script"
    bin/jboss-cli.sh --connect --file=$script
    # TODO the scripts that require a :reload, do we have to wait for the reload to finish as well??
done

# deploy the apps
for app in `ls $PROJECT/bin | egrep "\\.spring$|\\.war$"`; do
    bin/jboss-cli.sh --connect command="deploy $PROJECT/bin/$app"
done

# Wait for shutdown by user
read -p "Press any key to stop JBoss... " -n1 -s
$TARGET/bin/jboss-cli.sh --connect command=:shutdown
wait

